ARQUIVO_INICIAL_INPUT = "ARQUIVO_INICIAL_INPUT"
ARQUIVO_FINAL_INPUT = "ARQUIVO_FINAL_INPUT"

DATA_INICIO_INPUT = "DATA_INICIO_INPUT"
DATA_FIM_INPUT = "DATA_FIM_INPUT"

CONTAR_HORARIOS = "CONTAR_HORARIO"
CONTAR_LINHA = "CONTAR_LINHA"

NIVEL_AGREGACAO_DE_HORARIO_REGIAO = "AGREGACAO_HORARIO_REGIAO"
NIVEL_AGREGACAO_DE_HORARIO_OS = "AGREGACAO_HORARIO_OS"
NIVEL_AGREGACAO_DE_HORARIO_DIA = "AGREGACAO_HORARIO_DIA"
NIVEL_AGREGACAO_DE_HORARIO_MES = "AGREGACAO_HORARIO_MES"
NIVEL_AGREGACAO_DE_HORARIO_ANO = "AGREGACAO_HORARIO_ANO"
NIVEL_AGREGACAO_DE_HORARIO_EMPRESA = "AGREGACAO_HORARIO_EMPRESA"
NIVEL_AGREGACAO_DE_HORARIO_LINHA = "AGREGACAO_HORARIO_LINHA"

NIVEL_AGREGACAO_DE_LINHA_REGIAO = "AGREGACAO_LINHA_REGIAO"
NIVEL_AGREGACAO_DE_LINHA_OS = "AGREGACAO_LINHA_OS"
NIVEL_AGREGACAO_DE_LINHA_DIA = "AGREGACAO_LINHA_DIA"
NIVEL_AGREGACAO_DE_LINHA_MES = "AGREGACAO_LINHA_MES"
NIVEL_AGREGACAO_DE_LINHA_ANO = "AGREGACAO_LINHA_ANO"
NIVEL_AGREGACAO_DE_LINHA_EMPRESA = "AGREGACAO_LINHA_EMPRESA"

ERRO_INPUT_ARQUIVO = 'ERRO_INPUT_ARQUIVO'
ERRO_INPUT_DATAS = 'ERRO_INPUT_DATAS'
ERRO_FORMATO_ARQUIVO_INPUT = 'ERRO_FORMATO_ARQUIVO_INPUT'
ERRO_COLUNA_NECESSARIA_AUSENTE = 'ERRO_COLUNA_NECESSARIA_AUSENTE'
