COLUNA_CODIGO_EMPRESA = 'CODIGO_EMPRESA'
COLUNA_CODIGO_LINHA = 'CODIGO_LINHA'
COLUNA_NOME_LINHA = 'NOME_LINHA'
COLUNA_VIA = 'VIA'
COLUNA_HORARIO_IDA_SEMANA = 'HORARIO_IDA_SEMANA'
COLUNA_HORARIO_IDA_SABADO = 'HORARIO_IDA_SABADO'
COLUNA_HORARIO_IDA_DOMINGO = 'HORARIO_IDA_DOMINGO'
COLUNA_HORARIO_VOLTA_SEMANA = 'HORARIO_VOLTA_SEMANA'
COLUNA_HORARIO_VOLTA_SABADO = 'HORARIO_VOLTA_SABADO'
COLUNA_HORARIO_VOLTA_DOMINGO = 'HORARIO_VOLTA_DOMINGO'
COLUNA_DATA_INICIO = 'DATA_INICIO'
COLUNA_DATA_FIM = 'DATA_FIM'
COLUNA_OS = 'OS'
COLUNA_REGIAO = 'REGIAO'
COLUNA_DATA = 'DATA'

COLUNAS_HORARIOS = [
    COLUNA_HORARIO_IDA_SEMANA,
    COLUNA_HORARIO_IDA_SABADO,
    COLUNA_HORARIO_IDA_DOMINGO,
    COLUNA_HORARIO_VOLTA_SEMANA,
    COLUNA_HORARIO_VOLTA_SABADO,
    COLUNA_HORARIO_VOLTA_DOMINGO,
]

COLUNAS_INICIAIS = [
    COLUNA_CODIGO_EMPRESA,
    COLUNA_CODIGO_LINHA,
    COLUNA_NOME_LINHA,
    COLUNA_VIA,
    COLUNA_HORARIO_IDA_SEMANA,
    COLUNA_HORARIO_IDA_SABADO,
    COLUNA_HORARIO_IDA_DOMINGO,
    COLUNA_HORARIO_VOLTA_SEMANA,
    COLUNA_HORARIO_VOLTA_SABADO,
    COLUNA_HORARIO_VOLTA_DOMINGO,
    COLUNA_DATA_INICIO,
    COLUNA_DATA_FIM,
    COLUNA_OS,
    COLUNA_REGIAO,
]

COLUNAS_TABELA_HORARIA_DIARIA = COLUNAS_INICIAIS.copy()
COLUNAS_TABELA_HORARIA_DIARIA.remove(COLUNA_DATA_INICIO)
COLUNAS_TABELA_HORARIA_DIARIA.remove(COLUNA_DATA_FIM)
COLUNAS_TABELA_HORARIA_DIARIA.append(COLUNA_DATA)